name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        env:
          # Create a 'GH_TOKEN' secret in your repository with repo permissions for releases:
          # Settings → Secrets → Actions → New repository secret
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release

